### PR TITLE
feature/tests -> master

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ytime-shim-lambda/7)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/model_tests.py, line 268 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7#-Kw7ROrAdQ-zJ2coDTep:-Kw7ROrAdQ-zJ2coDTeq:b-ws1unl) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/c7cf20b4afe2873088546b6461afd67ae565a5e1/test/model_tests.py#L268)):*
> ```Python
>             "timesheet": {
>                 "punch": [
>                     {
> ```

Remove duplicate code by creating a function of some sort so that these can all be one line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by geogor37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/model_tests.py, line 268 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7#-Kw7ROrAdQ-zJ2coDTep:-KwHBWFJVohGOsF3L_xm:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/c7cf20b4afe2873088546b6461afd67ae565a5e1/test/model_tests.py#L268)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove duplicate code by creating a function of some sort so that these can all be one line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/model_tests.py, line 35 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7#-KwHJJR5aSnn6veCxSq4:-KwHJJR5aSnn6veCxSq5:bykgdfk) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/191b4383229ead63f7b1d029e437e863e2c911c0/test/model_tests.py#L35)):*
> ```Python
>         return job
> 
>     def create_status_dict (self, job_collection, international, period_total, weekly_total):
> ```

remove spaces after function names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by geogor37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/model_tests.py, line 35 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7#-KwHJJR5aSnn6veCxSq4:-KwHOxGSeDruBXORtG1h:b-4ofkyh) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/191b4383229ead63f7b1d029e437e863e2c911c0/test/model_tests.py#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

remove spaces after function names
</blockquote></details>

I reformatted the whole file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/model_tests.py, line 71 at r4](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7#-KwHX9EicPPUpxOgi8SA:-KwHX9EicPPUpxOgi8SB:b32jho9) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/5744e55c0f842052bfc3e1e55dd5cf7477af71d3/test/model_tests.py#L71)):*
> ```Python
> 
>     def get_bad_jobs(self):
>         bad_job1 = self.create_invalid_job_dict("Code Tester", "Y", "Y", "I", "Y", "Y", "0", "00:00", "00:00",
> ```

Move your line length in your preferences. Ask me if you need help with this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by geogor37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/model_tests.py, line 71 at r4](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7#-KwHX9EicPPUpxOgi8SA:-KwH_wJJ8gSjEiQMEhmV:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/5744e55c0f842052bfc3e1e55dd5cf7477af71d3/test/model_tests.py#L71)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move your line length in your preferences. Ask me if you need help with this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/7)*

**Pull request merged**
