### PR TITLE
feature/createPunch -> master

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ytime-shim-lambda/1)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/client.py, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1#-KsOkNeZ9FxKLfMQ9ZTJ:-KsOkNeZ9FxKLfMQ9ZTK:b-cjghb4) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/ae9e482988988cccbfe0d210d3ba2214ee4aa082/src/client.py#L25)):*
> ```Python
> 
> def punch_json(body):
>     [punch_date, punch_time] = body["punch_time"].split(" ")
> ```

Are we missing a try? What would happen if "punch_time" wasn't in the request?

---

*[test/my_tests.py, line 61 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1#-KsOkUs-5AR40w91rd1m:-KsOkUs-5AR40w91rd1n:b8tp0mp) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/ae9e482988988cccbfe0d210d3ba2214ee4aa082/test/my_tests.py#L61)):*
> ```Python
>         body = '{{"employee_record":"1", "latitude": "40.2523821","longitude": "-111.6576999", "clock_in":true, "punch_time": "{}"}}'.format(
>             datetime.today().strftime("%Y-%m-%d %H.%M"))
>         self.setupEvent("/punch", "POST", body = body)
> ```

Go ahead and inline it again (now that it's working)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1)*

**Comment by geogor37** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/client.py, line 25 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1#-KsOkNeZ9FxKLfMQ9ZTJ:-KsOpc9JtyYwFutc9hyX:b-80fkhg) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/ae9e482988988cccbfe0d210d3ba2214ee4aa082/src/client.py#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Are we missing a try? What would happen if "punch_time" wasn't in the request?
</blockquote></details>

Done. I just added one.

---

*[test/my_tests.py, line 61 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1#-KsOkUs-5AR40w91rd1m:-KsOl3v4oaDWChPeb9oa:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/ae9e482988988cccbfe0d210d3ba2214ee4aa082/test/my_tests.py#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Go ahead and inline it again (now that it's working)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/my_tests.py, line 61 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1#-KsOkUs-5AR40w91rd1m:-KsOqmcdvbl4uZcOamCl:b-9lzk8c) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/ae9e482988988cccbfe0d210d3ba2214ee4aa082/test/my_tests.py#L61)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove the excess newline as well. This probably got added in because your settings are different

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1)*

**Comment by geogor37** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/my_tests.py, line 61 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1#-KsOkUs-5AR40w91rd1m:-KsOrL-bBAHPAOv3Jya-:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/ae9e482988988cccbfe0d210d3ba2214ee4aa082/test/my_tests.py#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove the excess newline as well. This probably got added in because your settings are different
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/1)*

**Pull request merged**
