### PR TITLE
feature/timesheet -> master

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/ytime-shim-lambda/3)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/model_tests.py, line 8 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOHPLPmXXoh1bYn17:-KvdOHPLPmXXoh1bYn18:bii233e) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L8)):*
> ```Python
>     def test_get_minutes(self):
>         test_day = model.Day("2017-10-04")
>         good_punch1 = {"punch_time": "00.00.00.00"}
> ```

Are we taking seconds into the comparison right now? Would 00.00.59.99 be deletable if there were a 00.10.00.00?

---

*[test/model_tests.py, line 24 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdONJnZH85xfHFPZu5:-KvdONJnZH85xfHFPZu6:b-tu7ozi) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L24)):*
> ```Python
>         self.assertEqual(test_day.get_minutes(good_punch5), 510)
>         self.assertEqual(test_day.get_minutes(good_punch6), 483)
>         with self.assertRaises(ServiceException):
> ```

Did we get this working? What was the issue?

---

*[test/model_tests.py, line 36 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOQFHM7PO3ZDno-Rd:-KvdOQFHM7PO3ZDno-Re:b-y3s2bp) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L36)):*
> ```Python
>         test_day = model.Day("2017-10-04")
> 
>         punch1 = {"clock_in": True,
> ```

Reformat these so that there aren't new lines in all of these dictionaries

---

*[test/model_tests.py, line 80 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOW9mOMsmWgGAP4Kp:-KvdOW9mOMsmWgGAP4Kq:bpgqj9r) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L80)):*
> ```Python
>     def test_add_punch(self):
>         test_day = model.Day("2017-10-04")
>         good_punch1 = {"punch_type": "In",
> ```

Reformat

---

*[test/model_tests.py, line 131 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOYugeSgocYr_lzyU:-KvdOYugeSgocYr_lzyV:biog17n) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L131)):*
> ```Python
>         with self.assertRaises(ServiceException):
>             test_day.add_punch(bad_punch3)
>         self.assertEqual(len(test_day.punches), 4)
> ```

Add new line to end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/model_tests.py, line 8 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOHPLPmXXoh1bYn17:-Kvht8zHKjWrJ2MGZg3h:bjkut9t) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L8)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Are we taking seconds into the comparison right now? Would 00.00.59.99 be deletable if there were a 00.10.00.00?
</blockquote></details>

Not currently.  Your example would be deletable because the difference between the minute values is less than or equal to 10.  As such the values 00.10.59.99 and 00.00.10.00 would also both be deletable because the difference between the minute values is less than or equal to 10 even though they're technically more than 10 minutes apart.  Should we be taking the seconds into account here?

---

*[test/model_tests.py, line 24 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdONJnZH85xfHFPZu5:-KvhprOQ8X5t8OTUUWmE:baorh80) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did we get this working? What was the issue?
</blockquote></details>

I changed the import statement at the top from `from src import model` to just `import model` and it started working.  I don't understand why that solved it, but it did

---

*[test/model_tests.py, line 36 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOQFHM7PO3ZDno-Rd:-Kvhr72I9H5ljL13rcN-:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reformat these so that there aren't new lines in all of these dictionaries
</blockquote></details>

Done.

---

*[test/model_tests.py, line 80 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOW9mOMsmWgGAP4Kp:-Kvhr7_Bfgf_xOQT4ezJ:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L80)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reformat
</blockquote></details>

Done.

---

*[test/model_tests.py, line 131 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOYugeSgocYr_lzyU:-Kvhr8C2zjYvmf9iC_Nz:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L131)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add new line to end of file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/model_tests.py, line 8 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOHPLPmXXoh1bYn17:-KvjGbvjr0gFCsLGC4CM:b24yvvz) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L8)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Not currently.  Your example would be deletable because the difference between the minute values is less than or equal to 10.  As such the values 00.10.59.99 and 00.00.10.00 would also both be deletable because the difference between the minute values is less than or equal to 10 even though they're technically more than 10 minutes apart.  Should we be taking the seconds into account here?
</blockquote></details>

Yeah, we should, because I'm sure the desktop does...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Comment by geogor37** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/model_tests.py, line 8 at r1](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvdOHPLPmXXoh1bYn17:-Kvm8n_9XXYD2LF-VI_v:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/51a7f725fd0d8230f83cc494ee53ec7550a817cf/test/model_tests.py#L8)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yeah, we should, because I'm sure the desktop does...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model.py, line 95 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvmI1G8IZveeCgjDTRZ:-KvmI1G9GiNSYGIDtxQg:b-2a7ij1) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/e5be72d2795679c2ec9313192a8e7e75c4e905ea/src/model.py#L95)):*
> ```Python
>     def get_minutes(self, punch):
>         try:
>             parts = punch["punch_time"].split(".")
> ```

Why did we remove the str() around the punch["punch_time"]? That made it handle integer values, correct? Did we decide that we shouldn't be able to handle number input anymore? I guess that makes sense if we're using all three parts now....

---

*[test/model_tests.py, line 5 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvmIFFzU673e99jQ5uD:-KvmIFFzU673e99jQ5uE:b509tzc) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/e5be72d2795679c2ec9313192a8e7e75c4e905ea/test/model_tests.py#L5)):*
> ```Python
> from service_exception import ServiceException
> ```

Remove excess line

---

*[test/model_tests.py, line 23 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvmIMgJmKSKy2SIp6L8:-KvmIMgJmKSKy2SIp6L9:bnush48) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/e5be72d2795679c2ec9313192a8e7e75c4e905ea/test/model_tests.py#L23)):*
> ```Python
>         self.assertEqual(test_day.get_minutes(good_punch3), 510)
>         self.assertEqual(test_day.get_minutes(good_punch4), 1439)
>         self.assertAlmostEqual(test_day.get_minutes(good_punch5), 510.98, 2)
> ```

Haha- WHAT? What is assertAlmostEqual?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model.py, line 95 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvmI1G8IZveeCgjDTRZ:-KvmIlrl7sop8DFs8mvg:b-fj0u4q) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/e5be72d2795679c2ec9313192a8e7e75c4e905ea/src/model.py#L95)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we remove the str() around the punch["punch_time"]? That made it handle integer values, correct? Did we decide that we shouldn't be able to handle number input anymore? I guess that makes sense if we're using all three parts now....
</blockquote></details>

Yeah I took it out since numbers with the two decimals wouldn't be valid integers

---

*[test/model_tests.py, line 5 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvmIFFzU673e99jQ5uD:-KvmKdF9xD8QtxGs4bgV:b-896fix) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/e5be72d2795679c2ec9313192a8e7e75c4e905ea/test/model_tests.py#L5)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove excess line
</blockquote></details>

Done.

---

*[test/model_tests.py, line 23 at r3](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3#-KvmIMgJmKSKy2SIp6L8:-KvmJ2hIGOcMnE3ZBk_X:b-6frlk0) ([raw file](https://github.com/byu-oit/ytime-shim-lambda/blob/e5be72d2795679c2ec9313192a8e7e75c4e905ea/test/model_tests.py#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Haha- WHAT? What is assertAlmostEqual?
</blockquote></details>

Haha it tests that the number is equal out to the number of places you specify in the third argument.  For example, here it actually returns 510.983333333... so assertEquals was failing.  So I looked up how to assertEquals for these kinds of numbers, and I found this method :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/ytime-shim-lambda/3)*

**Pull request merged**
